<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>srec</AssemblyName>
    <RootNamespace>SteamClipRemuxer.Cli</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SteamClipRemuxer.Core/SteamClipRemuxer.Core.csproj" />
  </ItemGroup>
</Project>
